const chats = [
  {
    id: crypto.randomUUID(),
    icon: "👩🏻‍💻",
    chatHeading: "Kingswood Firs Job",
    lastSender: "Gary",
    lastMessage: "I'm going to be late",
    lastMessageTime: "10:30am",
    unreadMessageCount: 2,
  },
  {
    id: crypto.randomUUID(),
    icon: "👩🏻‍💻",
    chatHeading: "Beautiful Barlows",
    lastSender: "Adam",
    lastMessage: "Can you collect the cakes?",
    lastMessageTime: "19:12am",
    unreadMessageCount: 0,
  },
  {
    id: crypto.randomUUID(),
    icon: "👩🏻‍💻",
    chatHeading: "Freemans",
    lastSender: "Stu",
    lastMessage: "Brilliant",
    lastMessageTime: "22:53am",
    unreadMessageCount: 0,
  },
  {
    id: crypto.randomUUID(),
    icon: "👩🏻‍💻",
    chatHeading: "Kingswood Firs Job",
    lastSender: "Gary",
    lastMessage: "I'm going to be late",
    lastMessageTime: "10:30am",
    unreadMessageCount: 2,
  },
  {
    id: crypto.randomUUID(),
    icon: "👩🏻‍💻",
    chatHeading: "Beautiful Barlows",
    lastSender: "Adam",
    lastMessage: "Can you collect the cakes?",
    lastMessageTime: "19:12am",
    unreadMessageCount: 0,
  },
  {
    id: crypto.randomUUID(),
    icon: "👩🏻‍💻",
    chatHeading: "Freemans",
    lastSender: "Stu",
    lastMessage: "Brilliant",
    lastMessageTime: "22:53am",
    unreadMessageCount: 0,
  },
  {
    id: crypto.randomUUID(),
    icon: "👩🏻‍💻",
    chatHeading: "Kingswood Firs Job",
    lastSender: "Gary",
    lastMessage: "I'm going to be late",
    lastMessageTime: "10:30am",
    unreadMessageCount: 2,
  },
  {
    id: crypto.randomUUID(),
    icon: "👩🏻‍💻",
    chatHeading: "Beautiful Barlows",
    lastSender: "Adam",
    lastMessage: "Can you collect the cakes?",
    lastMessageTime: "19:12am",
    unreadMessageCount: 0,
  },
  {
    id: crypto.randomUUID(),
    icon: "👩🏻‍💻",
    chatHeading: "Freemans",
    lastSender: "Stu",
    lastMessage: "Brilliant",
    lastMessageTime: "22:53am",
    unreadMessageCount: 0,
  },
  {
    id: crypto.randomUUID(),
    icon: "👩🏻‍💻",
    chatHeading: "Kingswood Firs Job",
    lastSender: "Gary",
    lastMessage: "I'm going to be late",
    lastMessageTime: "10:30am",
    unreadMessageCount: 2,
  },
  {
    id: crypto.randomUUID(),
    icon: "👩🏻‍💻",
    chatHeading: "Beautiful Barlows",
    lastSender: "Adam",
    lastMessage: "Can you collect the cakes?",
    lastMessageTime: "19:12am",
    unreadMessageCount: 0,
  },
  {
    id: crypto.randomUUID(),
    icon: "👩🏻‍💻",
    chatHeading: "Freemans",
    lastSender: "Stu",
    lastMessage: "Brilliant",
    lastMessageTime: "22:53am",
    unreadMessageCount: 0,
  },
  {
    id: crypto.randomUUID(),
    icon: "👩🏻‍💻",
    chatHeading: "Kingswood Firs Job",
    lastSender: "Gary",
    lastMessage: "I'm going to be late",
    lastMessageTime: "10:30am",
    unreadMessageCount: 2,
  },
  {
    id: crypto.randomUUID(),
    icon: "👩🏻‍💻",
    chatHeading: "Beautiful Barlows",
    lastSender: "Adam",
    lastMessage: "Can you collect the cakes?",
    lastMessageTime: "19:12am",
    unreadMessageCount: 0,
  },
  {
    id: crypto.randomUUID(),
    icon: "👩🏻‍💻",
    chatHeading: "Freemans",
    lastSender: "Stu",
    lastMessage: "Brilliant",
    lastMessageTime: "22:53am",
    unreadMessageCount: 0,
  },
  {
    id: crypto.randomUUID(),
    icon: "👩🏻‍💻",
    chatHeading: "Kingswood Firs Job",
    lastSender: "Gary",
    lastMessage: "I'm going to be late",
    lastMessageTime: "10:30am",
    unreadMessageCount: 2,
  },
  {
    id: crypto.randomUUID(),
    icon: "👩🏻‍💻",
    chatHeading: "Beautiful Barlows",
    lastSender: "Adam",
    lastMessage: "Can you collect the cakes?",
    lastMessageTime: "19:12am",
    unreadMessageCount: 0,
  },
  {
    id: crypto.randomUUID(),
    icon: "👩🏻‍💻",
    chatHeading: "Freemans",
    lastSender: "Stu",
    lastMessage: "Brilliant",
    lastMessageTime: "22:53am",
    unreadMessageCount: 0,
  },
  {
    id: crypto.randomUUID(),
    icon: "👩🏻‍💻",
    chatHeading: "Kingswood Firs Job",
    lastSender: "Gary",
    lastMessage: "I'm going to be late",
    lastMessageTime: "10:30am",
    unreadMessageCount: 2,
  },
  {
    id: crypto.randomUUID(),
    icon: "👩🏻‍💻",
    chatHeading: "Beautiful Barlows",
    lastSender: "Adam",
    lastMessage: "Can you collect the cakes?",
    lastMessageTime: "19:12am",
    unreadMessageCount: 0,
  },
  {
    id: crypto.randomUUID(),
    icon: "👩🏻‍💻",
    chatHeading: "Freemans",
    lastSender: "Stu",
    lastMessage: "Brilliant",
    lastMessageTime: "22:53am",
    unreadMessageCount: 0,
  },
  {
    id: crypto.randomUUID(),
    icon: "👩🏻‍💻",
    chatHeading: "Kingswood Firs Job",
    lastSender: "Gary",
    lastMessage: "I'm going to be late",
    lastMessageTime: "10:30am",
    unreadMessageCount: 2,
  },
  {
    id: crypto.randomUUID(),
    icon: "👩🏻‍💻",
    chatHeading: "Beautiful Barlows",
    lastSender: "Adam",
    lastMessage: "Can you collect the cakes?",
    lastMessageTime: "19:12am",
    unreadMessageCount: 0,
  },
  {
    id: crypto.randomUUID(),
    icon: "👩🏻‍💻",
    chatHeading: "Freemans",
    lastSender: "Stu",
    lastMessage: "Brilliant",
    lastMessageTime: "22:53am",
    unreadMessageCount: 0,
  },
  {
    id: crypto.randomUUID(),
    icon: "👩🏻‍💻",
    chatHeading: "Kingswood Firs Job",
    lastSender: "Gary",
    lastMessage: "I'm going to be late",
    lastMessageTime: "10:30am",
    unreadMessageCount: 2,
  },
  {
    id: crypto.randomUUID(),
    icon: "👩🏻‍💻",
    chatHeading: "Beautiful Barlows",
    lastSender: "Adam",
    lastMessage: "Can you collect the cakes?",
    lastMessageTime: "19:12am",
    unreadMessageCount: 0,
  },
  {
    id: crypto.randomUUID(),
    icon: "👩🏻‍💻",
    chatHeading: "Freemans",
    lastSender: "Stu",
    lastMessage: "Brilliant",
    lastMessageTime: "22:53am",
    unreadMessageCount: 0,
  },
  {
    id: crypto.randomUUID(),
    icon: "👩🏻‍💻",
    chatHeading: "Kingswood Firs Job",
    lastSender: "Gary",
    lastMessage: "I'm going to be late",
    lastMessageTime: "10:30am",
    unreadMessageCount: 2,
  },
  {
    id: crypto.randomUUID(),
    icon: "👩🏻‍💻",
    chatHeading: "Beautiful Barlows",
    lastSender: "Adam",
    lastMessage: "Can you collect the cakes?",
    lastMessageTime: "19:12am",
    unreadMessageCount: 0,
  },
  {
    id: crypto.randomUUID(),
    icon: "👩🏻‍💻",
    chatHeading: "Freemans",
    lastSender: "Stu",
    lastMessage: "Brilliant",
    lastMessageTime: "22:53am",
    unreadMessageCount: 0,
  },
];

let messages = [
  {
    id: 1,
    message: "Hi, how are you?",
    date: new Date("2021-03-01T12:00:00"),
    sender: "me",
  },
  {
    id: 2,
    message: "Im good thanks",
    date: new Date("2021-03-01T12:00:02"),
    sender: "sam",
  },
  {
    id: 3,
    message: "And you?",
    date: new Date("2021-03-01T12:00:05"),
    sender: "sam",
  },
  {
    id: 4,
    message: "Feeling fab today",
    date: new Date("2021-03-01T12:00:07"),
    sender: "me",
  },
  {
    id: 5,
    message: "Feeling fab So what you up to today?",
    date: new Date("2021-03-01T12:02:14"),
    sender: "me",
  },
  {
    id: 6,
    message: "Not much just working on a project",
    date: new Date("2021-03-01T12:02:18"),
    sender: "sam",
  },
];

const sample = {
  chats,
  messages: messages.reverse(),
};
export { sample };
