/* eslint-disable prefer-template */
const chats = [
  {
    id: '1',
    chatHeading: 'Kingswood Firs Job',
    lastSender: 'Gary',
    lastMessage: "I'm going to be late",
    lastMessageTime: '10:30am',
    unreadMessageCount: 2,
    contacts: ['Gary', 'Rich', 'Harry', 'Sam', 'Tom', 'Stu'],
  },
  {
    id: (Math.random().toString(16) + '000000000').substring(2, 15),
    chatHeading: 'Beautiful Barlows',
    lastSender: 'Adam',
    lastMessage: "Can you collect the cakes? I'm stuck in traffic and it's going to be a long time before I'm home.",
    lastMessageTime: '19:12am',
    unreadMessageCount: 0,
    contacts: ['Adam', 'Becky', 'Maz', 'Ross', 'Sam', 'Stu'],
  },
  {
    id: (Math.random().toString(16) + '000000000').substring(2, 15),
    chatHeading: 'Freemans',
    lastSender: 'Stu',
    lastMessage: 'Brilliant 😀',
    lastMessageTime: '22:53am',
    unreadMessageCount: 0,
    contacts: ['Harry', 'Tom', 'Sam', 'Stu'],
  },
  {
    id: (Math.random().toString(16) + '000000000').substring(2, 15),
    chatHeading: 'John',
    lastSender: 'John',
    lastMessage: 'Never mind. No worries.',
    lastMessageTime: '21:12pm',
    unreadMessageCount: 0,
    contacts: ['John', 'Stu'],
  },
  {
    id: (Math.random().toString(16) + '000000000').substring(2, 15),
    chatHeading: 'Sam',
    lastSender: 'Stu',
    lastMessage: 'Love you too',
    lastMessageTime: '13:48am',
    unreadMessageCount: 0,
    contacts: ['Sam', 'Stu'],
  },
  {
    id: (Math.random().toString(16) + '000000000').substring(2, 15),
    chatHeading: 'Harry',
    lastSender: 'Stu',
    lastMessage: 'Sorted',
    lastMessageTime: '08:36am',
    unreadMessageCount: 0,
    contacts: ['Harry', 'Stu'],
  },
  {
    id: (Math.random().toString(16) + '000000000').substring(2, 15),
    chatHeading: 'Kingswood Firs Job',
    lastSender: 'Gary',
    lastMessage: "I'm going to be late",
    lastMessageTime: '10:30am',
    unreadMessageCount: 2,
    contacts: ['Gary', 'Rich', 'Harry', 'Sam', 'Tom', 'Stu'],
  },
  {
    id: (Math.random().toString(16) + '000000000').substring(2, 15),
    chatHeading: 'Beautiful Barlows',
    lastSender: 'Adam',
    lastMessage: "Can you collect the cakes? I'm stuck in traffic and it's going to be a long time before I'm home.",
    lastMessageTime: '19:12am',
    unreadMessageCount: 0,
    contacts: ['Adam', 'Becky', 'Maz', 'Ross', 'Sam', 'Stu'],
  },
  {
    id: (Math.random().toString(16) + '000000000').substring(2, 15),
    chatHeading: 'Freemans',
    lastSender: 'Stu',
    lastMessage: 'Brilliant 😀',
    lastMessageTime: '22:53am',
    unreadMessageCount: 0,
    contacts: ['Harry', 'Tom', 'Sam', 'Stu'],
  },
  {
    id: (Math.random().toString(16) + '000000000').substring(2, 15),
    chatHeading: 'John',
    lastSender: 'John',
    lastMessage: 'Never mind. No worries.',
    lastMessageTime: '21:12pm',
    unreadMessageCount: 0,
    contacts: ['John', 'Stu'],
  },
  {
    id: (Math.random().toString(16) + '000000000').substring(2, 15),
    chatHeading: 'Sam',
    lastSender: 'Stu',
    lastMessage: 'Love you too',
    lastMessageTime: '13:48am',
    unreadMessageCount: 0,
    contacts: ['Sam', 'Stu'],
  },
  {
    id: (Math.random().toString(16) + '000000000').substring(2, 15),
    chatHeading: 'Harry',
    lastSender: 'Stu',
    lastMessage: 'Sorted',
    lastMessageTime: '08:36am',
    unreadMessageCount: 0,
    contacts: ['Harry', 'Stu'],
  },
  {
    id: (Math.random().toString(16) + '000000000').substring(2, 15),
    chatHeading: 'Kingswood Firs Job',
    lastSender: 'Gary',
    lastMessage: "I'm going to be late",
    lastMessageTime: '10:30am',
    unreadMessageCount: 2,
    contacts: ['Gary', 'Rich', 'Harry', 'Sam', 'Tom', 'Stu'],
  },
  {
    id: (Math.random().toString(16) + '000000000').substring(2, 15),
    chatHeading: 'Beautiful Barlows',
    lastSender: 'Adam',
    lastMessage: "Can you collect the cakes? I'm stuck in traffic and it's going to be a long time before I'm home.",
    lastMessageTime: '19:12am',
    unreadMessageCount: 0,
    contacts: ['Adam', 'Becky', 'Maz', 'Ross', 'Sam', 'Stu'],
  },
  {
    id: (Math.random().toString(16) + '000000000').substring(2, 15),
    chatHeading: 'Freemans',
    lastSender: 'Stu',
    lastMessage: 'Brilliant 😀',
    lastMessageTime: '22:53am',
    unreadMessageCount: 0,
    contacts: ['Harry', 'Tom', 'Sam', 'Stu'],
  },
  {
    id: (Math.random().toString(16) + '000000000').substring(2, 15),
    chatHeading: 'John',
    lastSender: 'John',
    lastMessage: 'Never mind. No worries.',
    lastMessageTime: '21:12pm',
    unreadMessageCount: 0,
    contacts: ['John', 'Stu'],
  },
  {
    id: (Math.random().toString(16) + '000000000').substring(2, 15),
    chatHeading: 'Sam',
    lastSender: 'Stu',
    lastMessage: 'Love you too',
    lastMessageTime: '13:48am',
    unreadMessageCount: 0,
    contacts: ['Sam', 'Stu'],
  },
  {
    id: (Math.random().toString(16) + '000000000').substring(2, 15),
    chatHeading: 'Harry',
    lastSender: 'Stu',
    lastMessage: 'Sorted',
    lastMessageTime: '08:36am',
    unreadMessageCount: 0,
    contacts: ['Harry', 'Stu'],
  },
];

const messages = [
  {
    chatId: '1',
    id: 1,
    message: 'Hi, how are you?',
    date: new Date('2021-03-01T12:00:00'),
    sender: 'me',
  },
  {
    chatId: '1',
    id: 2,
    message: 'Im good thanks',
    date: new Date('2021-03-01T12:00:02'),
    sender: 'sam',
  },
  {
    chatId: '1',
    id: 3,
    message: 'And you?',
    date: new Date('2021-03-01T12:00:05'),
    sender: 'sam',
  },
  {
    chatId: '1',
    id: 4,
    message: 'Feeling fab today',
    date: new Date('2021-03-01T12:00:07'),
    sender: 'me',
  },
  {
    chatId: '1',
    id: 5,
    message: 'Feeling fab So what you up to today?',
    date: new Date('2021-03-01T12:02:14'),
    sender: 'me',
  },
  {
    chatId: '1',
    id: 6,
    message: 'Not much just working on a project',
    date: new Date('2021-03-01T12:02:18'),
    sender: 'sam',
  },
];

const sample = {
  chats,
  messages: messages.reverse(),
};
export default sample;
